README

In particular
* wking/rss2email#72
* wking/rss2email#78
* wking/rss2email#82
* wking/rss2email#85
* wking/rss2email#86
* wking/rss2email#89

Transfer some PRs from wking/rss2email/

---

HACKING.md
nix/nixpkgs.nix
nix/release.nix
shell.nix

These are intended to ease setting up a valid development environment.
They require installing the nix package manager, so they are optional.

Add nix files & a description of what they do

---

README.rst

For sake of better discoverability and for pypi.

doc: add better documentation about post-processing

---

rss2email/command.py
rss2email/config.py

fix: enable to debug the name of the feed that times-out

---

.travis.yml
nix/nixpkgs.nix
nix/release.nix
rss2email/command.py
test/test.py

This adds a basic travis CI setup.
It also fixes the code so that it works down to python 3.5 (again)
Closes #12

Ci add travis nix config

---

HACKING.md

- Make the text flow a bit better.
- Update the `nix/release.nix` build instructions

HACKING.md: update nix section

---

r2e.1
rss2email/config.py
test/allthingsrss/3.expected
test/allthingsrss/4.expected

This uses the correct path for the html2text config options.

fix html2text config options

---

rss2email/command.py
test/test.py

Fix opmlexport output file writing

---

CHANGELOG
rss2email/feeds.py

Fixes #126. It was my fault.
@Ekleog, could you make a release 3.12.2, please?

Fix bug #126.

---

.github/workflows/python-package.yml
CHANGELOG
HACKING.md
nix/release.nix
requirements.txt
rss2email/email.py
rss2email/feed.py
setup.py
test/data/disqus/1.expected

Support feedparser 6.

---

.github/workflows/python-package.yml
poetry.lock
pyproject.toml
requirements.txt
shell.nix

Currently the tests are broken in nix-shell because feedparser was
updated to depend on 6.0.0 which is not yet in nixpkgs. This resolves
that issue and will make dependency resolution easier to manage going
forward.

Poetry2nix

---

CHANGELOG
rss2email/feeds.py

Only look in $XDG_DATA_HOME
Fixes #164

Stop looking in $XDG_DATA_DIRS for the database

---

CHANGELOG
rss2email/feed.py

Make warnings about html content-type properly display

---

rss2email/feed.py

Add HTTPS proxy support

---

CHANGELOG
r2e.1
rss2email/config.py
test/data/allthingsrss/6.config
test/data/allthingsrss/6.expected

Add wrap-links option to prevent links from wrapping over multiple lines

---

.github/workflows/python-package.yml
poetry.lock
pyproject.toml
setup.py

Fixes #178
Fixes #84
Replaces #181, because upstream feedparser released the proposed fix. Please merge only one of the PRs and close the other, noting that 2 of the 3 commits in each of the PRs are identical.

Update feedparser to fix various issues

---

rss2email/command.py
rss2email/feeds.py

I believe this fixes #110 , it's working fine on my system at least.

Don't rewrite config file when fetching feeds

---

CHANGELOG
rss2email/config.py

Remove support for '$' interpolation in config file.

---

rss2email/error.py

I did not reproduced those (as the require argument is never True, should it be dropped?), I just noticed the issue while reading the code.

In case those error occur, the datafile does not exist (.datafile is None), print its path instead.

---

CHANGELOG

Fixes https://github.com/rss2email/rss2email/pull/182#discussion_r820204939.

Fix CHANGELOG for unreleased 1.14/2.0

---

rss2email/post_process/prettify.py

307 is pickle enchancments while 370 is the per-user site-packages mentioned in the comment.

Change PEP 307 to 370 in prettify post-process comment.

---

README.rst

This fixes the badges at the top of the README, which were reported broken in #206.

Fix README badges

---

r2e.1
rss2email/config.py

https://github.com/rss2email/rss2email/pull/60

Document same-server-fetch-interval

---

pyproject.toml

See https://archlinux.org/todo/use-correct-pep517-build-system/

Use poetry-core as build-backend

---

rss2email/email.py
rss2email/feed.py
rss2email/feeds.py
rss2email/util.py
test/test.py

the doctests are not run in CI and a few of them are rotten
this PR fixes this.
going from 42 tests to 57 tests.

test: run doctest in CI & fix rotten doctest tests
