.update-copyright.conf, AUTHORS, CHANGELOG, HACKING.md, r2e.1, rss2email/__init__.py, rss2email/command.py, rss2email/config.py, rss2email/email.py, rss2email/error.py, rss2email/feed.py, rss2email/feeds.py, rss2email/main.py, rss2email/post_process/prettify.py, rss2email/post_process/redirect.py, setup.py
Seems fitting if we move to a community-maintained project.
=> Change main project author to “the rss2email maintainers” and drop maintainer list in setup.py

rss2email/feed.py
Sometimes, id is present after feed parsing but remains empty, leading to empty history on saving.
So we fetch all feeds again and again when there is a new one.
=> Feed id may be present but is empty

setup.py
851d9835fb73632717c97d03b7655a0039527ba4 renamed README to README.rst but
didn't update setup.py to point to the new name.
=> update reference to README.rst in setup.py

rss2email/feeds.py
If your home is on NFS (as mine is), you get this error when we try to lock the data file:
```
Traceback (most recent call last):
File "/home/kaashif/.local/bin/r2e", line 5, in <module>
rss2email.main.run()
File "/home/kaashif/.local/lib/python3.6/site-packages/rss2email/main.py", line 168, in run
feeds.load(lock=lock)
File "/home/kaashif/.local/lib/python3.6/site-packages/rss2email/feeds.py", line 247, in load
self._load_feeds(lock=lock, require=require)
File "/home/kaashif/.local/lib/python3.6/site-packages/rss2email/feeds.py", line 270, in _load_feeds
_fcntl.flock(self._datafile_lock.fileno(), locktype)
OSError: [Errno 9] Bad file descriptor
```
This is because Python's `fcntl.flock` uses the `flock` syscall, which doesn't work on NFS. We can instead use Python `fcntl.lockf`, which …
=> Use lockf so locking data file works on NFS (fixes #10)

rss2email/command.py, rss2email/config.py, rss2email/feed.py, test/test.py
This adds the `same-server-fetch-interval` config key, which lets the user specify a sleep interval between consecutive fetches from the same server. This would fix the problem described in #53. I think it is generally a good idea to avoid being an obnoxious client, and this contributes to that.
I'm not convinced I added the config key correctly, I think someone should look this over - I have only a vague understanding of the code. I have tested it and it seems to work though.
=> Add sleep interval between fetches from same server (closes #53)

rss2email/feed.py
Since html2text new release deprecated the unescape function whoever
relays on the new version of library will face an unhandled exception.
Since Python 3.4 there's a built-in version of similarly functioning code
in html module.
I replaced one for the other.
related to https://github.com/rss2email/rss2email/issues/63
=> Replacing html2text.unescape with html.unescape

r2e.1
I saw a comment on #28 about how this is one of (or maybe the only) thing blocking a release, so I decided to help, based on the work from @Profpatsch.
I can't see anything important missing: all options and commands are documented, along with all config keys (as far as I can tell). Maybe we could do with some examples or something, but that shouldn't be enough to block a release.
If there's anything incorrect, let me know. My personal opinion is that we should cut a new release as soon as humanly possible so that people (mainly package maintainers) know the project is still alive and so all of the years of unreleased fixes finally get released in some form.
=> Update man page, closes #2

CHANGELOG
I think these are the last significant things that need to be added to the changelog.
I think 3.10 is ready for release now, someone with the rights should make a release on GitHub and PyPI after the changelog is updated. I could do it on GitHub but I'm not a maintainer on PyPI so I can't do it there.
Let me know if anything is missing.
=> Update changelog for v3.10

rss2email/feed.py
60% of feeds don't have a version tag and that's no problem at all.
no need to produce a warning.
=> improve logging

rss2email/feed.py
Just finished a really hard debug session due to guid.
It is confusing that:
* the handling of guid is spread over two methods `_process_entry` and `_get_entry_id`.
* the test for "entry already seen" mixes two strategies configured differently `if guid in self.seen` and `if self.seen[guid]['id'] == id_:`
* the debug information through `LOG.debug` and `X-RSS-ID` does not correspond to the setting in the config file
This pull request solves those three problems:
* the handling of guid is fully encapsulated in `_get_entry_id`, with no exception or overriding.
* the key in `self.seen` is the unique decision procedure: `if guid in self.seen`
* all debug information rely on the `guid` as provided by `_get_entry_id` and configured by the config file
Fix #39
=> fix: clarify handling of guid in _process_entry

test/test.py
I restructured the tests to use `unittest` and wrote a test that runs r2e with `email-protocol = maildir` and checks the maildir for the messages. It works by actually starting a web server and actually having a real maildir on disk, there is no mocking here. I intend to do the same kind of thing with IMAP and SMTP.
I kept the old tests since they are still useful but maybe I'll rejig them to actually run r2e and not mess around with the internals so much. That will happen in a later PR.
=> Test maildir sending

AUTHORS, CHANGELOG, r2e.1, rss2email/config.py, rss2email/feed.py, test/allthingsrss/4.config, test/allthingsrss/4.expected
This PR adds the option to change the `User-Agent` string that is sent along with emails. I personally use `urlview` to filter the rss2email messages I receive, and wanted to avoid having the rss2email github link show up in every email. The new configuration parameter has the following default value:
user-agent = rss2email/_VERSION_ (https://github.com/rss2email/rss2email)
The `_VERSION_` part is replaced with the appropriate version number, meaning that the **default behavior is unchanged**. I also added a test (`test/allthingsrss/4.{config,expected}`). Thanks for considering this PR.
=> Allow configuration of User-Agent string

nix/release.nix, rss2email/util.py
When running r2e with Python 3.8 and specifying a post_process hook like `post-process = rss2email.post_process.prettify process`, the following exception occurs:
```
Traceback (most recent call last):
File "/usr/local/bin/r2e", line 5, in <module>
rss2email.main.run()
File "/usr/local/lib/python3.8/site-packages/rss2email/main.py", line 169, in run
args.func(feeds=feeds, args=args)
File "/usr/local/lib/python3.8/site-packages/rss2email/command.py", line 85, in run
feeds.save()
File "/usr/local/lib/python3.8/site-packages/rss2email/feeds.py", line 346, in save
feed.save_to_config()
File "/usr/local/lib/python3.8/site-packages/rss2email/feed.py", line 254, in save_to_config
value = self._get_configured_option_value(
File "/usr/local/lib/python3.8/site-packages/rss2email/feed.py", line 301, …
```
=> Python 3.8 compatibility

rss2email/command.py, rss2email/feed.py, rss2email/util.py, test/test.py
* Fixes invalid escape sequences deprecation warning.
* Use threading.is_alive for Python 3.9 compatibility.
Fixes #85
=> Python 3.9 compatibility fixes.

test/README
The r2e binary needs to be in scope for the tests to work.
Also, PYTHONPATH should not be overwritten.
=> test/README: fix command invocation

rss2email/feed.py, rss2email/post_process/redirect.py, test/test.py
This PR is the first few commits of #97, plus two tests that:
* The substituted values aren't written to the config file when you add a new feed
* Old badly substituted per-feed configs are corrected (this only happens if you added a feed in v3.11 and had the default user agent)
I think there's still some other stuff in #97 that would be good to pick up, mostly test improvements, but I think these bug fixes should be merged first. I'll make a PR later on to improve tests, I've done a bit of that in #94, but smaller PRs are easier to review (and take less time to make).
cc @jikamens
=> Fixes to the configurable user-agent changes introduced in 3.11

nix/release.nix, rss2email/feeds.py, rss2email/main.py, test/README, test/test.py
This PR corrects how the locking works, which caused issues in e.g. https://github.com/rss2email/rss2email/issues/83. The problem is outlined in a comment I wrote there but basically, the desired behaviour is that if there are multiple instances of r2e about, they should take it in turns to run and avoid all running at the same time, possibly mangling the data file or the config file.
I implement this by acquiring an exclusive lock on the data file right at the start and releasing it right at the end. As far as I can tell, this eliminates the error @ezbik was experiencing, but it's always possible I broke something else subtle.
Also, there is a branch that only happens if we're not on Solaris...I certainly hope no-one is.
=> Lock the datafile at the start, only release at the end

.github/workflows/python-package.yml, requirements.txt
This change comes after I saw #112 where a bug completely broke rss2email on Windows. We should run the tests on Windows and macOS to make sure this doesn't happen, since I'm only testing on Debian. I didn't do this through Travis since Travis doesn't support Python on Windows or macOS.
After this is merged, I think we should get rid of Travis CI completely, since it would be redundant and is in fact strictly worse than what is provided by GitHub actions. Also, my opinion is that the CI is much easier to understand if it's literally just `pip install -r requirements.txt; ./test/test.py -v` from a clean machine, since this is what I'm doing locally.
To see what a run of this looks like, see here for an example: https://github.com/kaashif/rss2email/runs/745685834
=> Add GitHub action to build and run tests on Ubuntu, Windows and macOS

rss2email/feed.py, test/allthingsrss/1.expected, test/allthingsrss/2.expected, test/allthingsrss/3.expected, test/allthingsrss/4.expected, test/bbc-chinese/1.expected, test/bbc-chinese/2.expected, test/disqus/1.expected, test/gmane/1.expected, test/gmane/2.expected, test/gmane/3.expected
This patch populates some standard List headers as defined in RFC2919 and RFC2369.
Those are commonly recognised by some MUAs, allowing automatic tagging and sorting.
=> add List-{ID,Post} headers to emails

rss2email/feeds.py
It doesn't seem to be used anywhere else in the code base.
=> Make read_configfiles a local variable

rss2email/error.py
TimeoutError is tightly coupled to TimeLimitedFunction, making it
unlikely the message parameter would ever be used by it or anything
else.
=> Remove unused TimeoutError message parameter.

CHANGELOG, rss2email/config.py, rss2email/email.py
This takes a path to a sendmail configuration file in case one does not
want to use the global configuration.
=> Add sendmail_config option

CHANGELOG, rss2email/main.py, test/test.py, test/util/execcontext.py
The verbose setting specified in the configuration file doesn't seem to
actually set the log level anywhere.
=> Set log level from configuration

r2e.1, rss2email/main.py
Current approach makes `r2e` create the lockfile under
`/tmp/rss2email.lock` if XDG_RUNTIME_DIR is unset, for all users,
making it impossible to use in shared shell environments. Instead,
create the lockfile under `/tmp/rss2email-${UID}/rss2email.lock`.
While there, document that XDG_RUNTIME_DIR is used for storing the
lockfile.
=> Create lockfile in an user-specific directory

CHANGELOG, rss2email/email.py, rss2email/error.py, test/test.py, test/util/tempsendmail.py
There's really no way to debug a broken sendmail setup when the output
is thrown away. Stdout and stderr were passed to the exception as
attributes but do not appear to be used there.
I don't believe there's any other good way to merge stdout/stderr and
preserve the sequential order than to pass one to the other and the
other to PIPE.
=> Log sendmail output

test/test.py
While working on #158 I found it hard to generate the `*.expected` files. So I looked at `test.py` and modified it:
- `run_single_test` has no `force`argument anymore. I don't know if there was any case in which it was passed, indeed.
- the equivalent of it is the environment variable `FORCE_TESTDATA_CREATION` ; set it to `1` and you are now in "force mode"
- in force mode, only _missing_ files are created. existing files are not overwritten
The workflow to create a test case is now much simpler:
- create `1.config` insde `data/mysuite/`
- run `env FORCE_TESTDATA_CREATION=1 python3 -m unittest`. This will show you which files have been created, reporting them as errors.
- Now you can run `python3 -m unittest` and it should pass
- Of course, you need to check if you like the result
- You …
=> Simplify test case creation

CHANGELOG, rss2email/config.py, rss2email/email.py, test/data/gmane/4.config, test/data/gmane/4.expected, test/data/tails/1.config, test/data/tails/1.expected, test/data/tails/2.config, test/data/tails/2.expected, test/data/tails/README, test/data/tails/feed.rss
This pull request adds support for creating `multipart/alternative` emails, thus fixing #101.
This support can be enabled with the `multipart-html` boolean option (defaults to False, see below).
It works like this:
* it does NOT modify `text/plain` messages
* whenever a `text/html` message is generated, a new `multipart/alternative` message is created. It preserves all the headers, add a mimepart for `text/html` from the original message and generates a new `text/plain` part using `html2text`
* given the way rss2email works, digest messages are properly transofmed: each message in the digest is now multipart/alternative.
I set `multipart-html` default to False for two reasons:
1. not to break current tests
2. not to change current behavior unexpectedly
Apart for these two reasons, I think …
=> #101: make HTML emails actually multipart/alternative

rss2email/email.py, rss2email/feed.py, test/data/bbc-chinese/3.config, test/data/bbc-chinese/3.expected
Before this patch, if the sender name included non-ASCII characters, and 'US-ASCII' was not the first in the user-configurable list of encodings, then the sender name would be doubly escaped, and the MUA would dutifully display an unfriendly From: =?utf-8?b?…?= <…@…> (see full explanation in the commit message). The fix is to let `formataddr` do its job and not to re-process its result.
The included new test case demonstrates nicely how the badly-encoded message looks like, when run with the old code.
=> Fix double escaping of sender names on certain configurations

CHANGELOG, r2e.1, rss2email/command.py, rss2email/feed.py, rss2email/main.py
Using `r2e run --clean` will remove seen entries no longer found in the feed, avoiding the race-condition with `r2e reset ; r2e run -n`. This option could also be used instead of `r2e run` to keep the database small, or used periodically due to it being a little slower.
Some feeds only show the N most recent items and if a recent item is removed from the feed it will cause an older item to reappear, and r2e will resend it. The second patch keeps the 3 most recent old entries and should be enough to never resend an old item.
Should there be a short -C option, or another letter since it resembles -c?
Fixes #49
=> Add option to remove seen entries no longer in the feed.

rss2email/feed.py
Not all MUA's support encoded date fields, Mutt doesn't and Thunderbird might not unless fixed since https://bugzilla.mozilla.org/show_bug.cgi?id=276199 decided it was an RFC violation.
=> add encode-date-field option to disable encoding for MUA's that lack support

pyproject.toml
Pip installation from VCS might ignore setup.py in favour of pyproject.toml,
hence the need for duplication.
=> Add r2e script to the poetry section in pyproject.toml

CHANGELOG, rss2email/feed.py, test/data/gmane/3.expected, test/data/gmane/4.expected, test/data/quiltville/1.expected, test/data/tails/2.expected
Has no effect on non-RTL text, or on feed items that have their `dir` attribute already set properly, but can help greatly with reading RTL items that neglect to specify the `dir` attribute.
See [the spec](https://html.spec.whatwg.org/multipage/dom.html#the-dir-attribute) for some hard-core technicalities, or scroll down to the example there for a visual demonstration.
I am opening this as a draft PR to gather comments, but will wait with rebasing until #174 is decided because of conflicting changes.
=> Set HTML attribute dir=auto on body element

CHANGELOG, rss2email/feed.py, test/data/fastmailstatus/1.config, test/data/fastmailstatus/1.expected, test/data/fastmailstatus/README, test/data/fastmailstatus/feed.rss, test/data/gmane/3.expected, test/data/gmane/4.expected, test/data/quiltville/1.expected, test/data/tails/2.expected
Before the regression, a URL of "None" was inserted in the href attribute, but with 4cdf574 (Perform HTML escaping on text to be appended to HTML, 2021-03-19) applied, calling saxutils.escape on None had crashed r2e with:
Traceback (most recent call last):
File "/rss2email/test/test.py", line 62, in fn
self.run_single_test(config_path=test_path)
File "/rss2email/test/test.py", line 135, in run_single_test
feed.run()
File "/rss2email/rss2email/feed.py", line 933, in run
for (guid, state, sender, message) in self._process(parsed):
File "/rss2email/rss2email/feed.py", line 394, in _process
processed = self._process_entry(parsed=parsed, entry=entry)
File "/rss2email/rss2email/feed.py", line 544, in _process_entry
content = self._process_entry_content(
File "/rss2email/rss2email/feed.py", line …
=> Fix crash on html-mail entries with no URL

CHANGELOG, r2e.1, rss2email/command.py, rss2email/main.py, test/test.py
Hi,
i've added a new option to the `add` command:  `--fetch` (short `-f`), to fetch/initialize a feed while adding.
The as-is alternative is a `add` and a `run --no-send` risking losing any other updates.
=> Add fetch option to add command

CHANGELOG, r2e.1, rss2email/config.py, rss2email/feed.py, test/data/allthingsrss/7.config, test/data/allthingsrss/7.expected
My mail provider prevents setting the `From` address, so I've been finding it difficult to quickly identify which feed a new email is from. This change adds a `subject-format` option that lets you configure the subject line to make that more apparent. I use `subject-format = {feed-name}: {feed-title}` which makes it much easier.
First contribution to the project, so happy to make changes if desired. Thanks.
=> Add subject format option

r2e.1
"\'" renders as an acute accent and just a "'" at the beginning of a
line is interpreted as Groff command. So reformat the line instead.
=> Fix manpage formating

README.rst
Looks like the new channel is #rss2email at libera.chat
=> Update IRC Channel from freenode to Libera

CHANGELOG, r2e.1, rss2email/feed.py, test/test.py
Based on work in and closes #209. Closes #120 and fixes #154 (ability to configure HTTP user agent). It also fixes a regression from version 3.11, where `feedparser` was used in the User-Agent for fetching feeds instead of the previously-used `rss2email`.
Read [this comment in the #209 thread](https://github.com/rss2email/rss2email/pull/209#issuecomment-1102715056) for the full context. The gist is in the commit message:
> It is worth noting that https://github.com/rss2email/rss2email/commit/f57513aa9868ce5d18148eb4eb787599c2b5d2fc (Use configured user-agent string and replace \_VERSION\_ with \_\_version\_\_ value, 2019-09-13) changed the semantics of the `user-agent` configuration unintentionally. This error was unfortunately added to the documentation in …
=> Fix a couple of HTTP user agent regressions

README.rst, r2e.1, rss2email/config.py, rss2email/email.py
When rss2email runs on the same host as the target mail server, then it is quite common that the server exposes a locally accessible LMTP socket. The LMTP protocol is quite similar to the SMTP protocol, but generally has no mail queue and thus requires no MDA. Instead, the mail is directly porcessed by the mail server without any intermediates.
Implement LMTP support such that it becomes possible to deliver mail to such servers directly.
=> Support sending mail via LMTP

rss2email/feed.py
Fixes #229 by not attempting to enumerate all non-error statuses explicitly.
While researching for this fix, I noticed that HTTP status 308 (Moved Permanently) is another form of permanent redirect and corrected the code to include that case. Note that currently feedparser does not handle HTTP status 308 as a redirect, but this will change when (hopefully) https://github.com/kurtmckee/feedparser/pull/326 gets merged and released there.
In addition, while I was in the area, I added handling of status 410 (Gone) in similar vein to the handling of permanent redirects, by marking the feed as inactive (as suggested [in the feedparser documentation](https://feedparser.readthedocs.io/en/latest/http-redirect.html#noticing-feeds-marked-gone)).
=> HTTP statuses cleanup
